spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      #ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug